# Generated by Django 4.2.4 on 2024-01-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.TextField()),
                ('archivo', models.FileField(upload_to='zip/')),
                ('cantidad', models.IntegerField()),
                ('carpeta', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='repositorio.carpeta')),
            ],
            options={
                'verbose_name': 'Compendio',
                'verbose_name_plural': 'Compendios',
                'db_table': 'compendio',
            },
        ),
    ]
