# Generated by Django 4.2.4 on 2024-01-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_compendio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compendio',
            name='activo',
        ),
        migrations.AddField(
            model_name='compendio',
            name='hash',
            field=models.TextField(default='NA'),
        ),
    ]
